- id: set_powerconsumptionheating
  alias: Set powerconsumtionheating
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: /10
    seconds: 0
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.powerconsumptionheating
      value: '{{(((states.sensor.power_heating.state | int / 10) | round(0)) | int
        * 10) +  ((range(1, 100) | random)/1000)}}'
- id: set_pricepowerconsumptionheating
  alias: Set price powerconsumptionheating
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: /10
    seconds: 30
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.pricepowerconsumptionheating
      value: '{{((((states.sensor.power_heating.state | int / 60) | round(0)) | int
        * 10) *  ((states.sensor.electricity_price_rognervegen_4a.state | float) +
        (states.sensor.nettleie.state | float))/1000) | round(3) + ((range(1, 100)
        | random)/100000)}}'
- id: zone_enter_workshop
  trigger:
    platform: zone
    entity_id: device_tracker.havard_sin_iphone_2
    zone: zone.verksted
    event: enter
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.verksted_zone_he
- id: zone_leave_workshop
  trigger:
    platform: zone
    entity_id: device_tracker.havard_sin_iphone_2
    zone: zone.verksted
    event: enter
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.verksted_zone_he
- id: auto_set_tod_ad
  alias: Set time of day after dark
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.tod_ad
  - service: input_boolean.turn_off
    entity_id: input_boolean.tod_day
  - service: frontend.set_theme
    data:
      name: homekit-dark
- id: auto_set_tod_ad_light
  alias: Set time of day after dark when light is low
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_light_level
    below: 2500
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.tod_day
      state: 'on'
    - condition: time
      after: '15:00:00'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.tod_ad
  - service: input_boolean.turn_off
    entity_id: input_boolean.tod_day
  - service: frontend.set_theme
    data:
      name: homekit-dark
- id: auto_set_tod_ad_15
  alias: Set time of day after dark 1500
  initial_state: true
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 5.0
    - condition: numeric_state
      entity_id: sensor.outdoor_light_level
      below: 2500
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.tod_ad
  - service: input_boolean.turn_off
    entity_id: input_boolean.tod_day
  - service: frontend.set_theme
    data:
      name: homekit-dark
- id: auto_set_tod_night
  alias: Set time of day night and cleanup
  initial_state: true
  trigger:
    platform: time
    at: 00:01:00
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.tod_night
  - service: input_boolean.turn_off
    entity_id:
    - input_boolean.tod_ad
    - input_boolean.tod_day
    - input_boolean.tod_morning
  - service: frontend.set_theme
    data:
      name: homekit-dark
- id: auto_set_tod_morning
  alias: Set time of day morning
  initial_state: true
  trigger:
    platform: time
    at: 05:45:00
  condition:
    condition: state
    entity_id: input_boolean.tod_night
    state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.tod_morning
  - service: input_boolean.turn_off
    entity_id: input_boolean.tod_night
  - service: frontend.set_theme
    data:
      name: homekit-light
- id: auto_set_tod_day
  alias: Set time of day day
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: +01:30:00
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.tod_day
  - service: input_boolean.turn_off
    entity_id:
    - input_boolean.tod_morning
    - input_boolean.tod_night
  - service: frontend.set_theme
    data:
      name: homekit-light
- id: outdoor_movement
  alias: ta opp ved utendørs bevegelse
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.outside_movement
    to: 'on'
  action:
    service: camera.record
    data:
      entity_id: camera.utendors
      filename: /config/www/videos/snapshot_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4
      duration: 20
      lookback: 10
- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - at: 00:00:00
    platform: time
  action:
  - data:
      addon: local_letsencrypt
    service: hassio.addon_restart
  initial_state: true
- id: startup_initial
  alias: Startup cleanup
  initial_state: false
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: homeassistant.turn_on
    entity_id:
    - input_boolean.kitchen_auto
    - input_boolean.livingroom_auto
    - input_boolean.bedroom_auto
    - input_boolean.bathroom_auto
    - input_boolean.guestbathroom_auto
    - input_boolean.guestbedroom_auto
    - input_boolean.hall_auto
    - input_boolean.walkway_auto
    - input_boolean.playroom_auto
    - input_boolean.kidsbedroom_auto
    - input_boolean.laundry_auto
    - input_boolean.workshop_auto
- id: update_morning_commute_sensor
  alias: Commute - Update morning commute sensor
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /5
    seconds: 0
  condition:
  - condition: time
    after: 07:00:00
    before: 09:00:00
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: homeassistant.update_entity
    data:
      entity_id: sensor.H_morning_comute
- id: update_evening_commute_sensor
  alias: Commute - Update evening commute sensor
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /5
    seconds: 0
  condition:
  - condition: time
    after: '15:00:00'
    before: '17:00:00'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: homeassistant.update_entity
    data:
      entity_id: sensor.H_evening_comute
