homeassistant:
  # name: Rognervegen 4
  # latitude: !secret ha_latitude
  # longitude: !secret ha_longitude
  # elevation: 100
  # unit_system: metric
  # time_zone: Europe/Oslo
  customize: !include customize.yaml
  customize_glob:
    "sensor*exporting*":
      hidden: true
      homebridge_hidden: true
    "sensor.alarm*":
      hidden: true
      homebridge_hidden: true
    "sensor.*power_management*":
      hidden: true
      homebridge_hidden: true
    "sensor.*nano*heat*":
      hidden: true
      homebridge_hidden: true
    "sensor*sourcenodeid*":
      hidden: true
      homebridge_hidden: true
    "sensor*burglar*":
      hidden: true
      homebridge_hidden: true
    "sensor*ultraviolet*":
      hidden: true
      homebridge_hidden: true
    "binary_sensor*_motion":
      device_class: motion
    "sensor*temperature":
      device_class: temperature
    "sensor*humidity":
      device_class: humidity
    "binary_sensor*door":
      device_class: door
    "sensor*illuminance":
      device_class: illuminance
  auth_providers:
  - type: trusted_networks
    trusted_networks:
      - 10.20.0.0/24
    trusted_users:
      10.20.0.71: 
        - c47a6deffa9543e3af5a7af576cce84a
      10.20.0.0/24: 
        - 9084c53be9f449c29ae4af0d35fba3fc
        - c47a6deffa9543e3af5a7af576cce84a
    allow_bypass_login: true
  - type: homeassistant
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

config:

http:
  base_url: !secret base_url
  server_port: 4343
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: True
  trusted_proxies:
    - 10.20.0.50

influxdb:
  host: 127.0.0.1
  username: "home-assistant"
  password: !secret flux_db_password
  include:
    domains:
      - sensor
      - input_boolean
      - binary_sensor
      - light
      - switch
      - weather
      - input_number
  default_measurement: state
  tags:
    instance: prod
    source: hass
    
zone:
  - name: Verksted
    latitude: !secret ha_latitude
    longitude: !secret ha_longitude
    radius: 3
    passive: true
  - name: Kjøkken
    latitude: !secret ha_latitude
    longitude: !secret ha_longitude
    radius: 6
    passive: true

apple_tv:

updater:
  include_used_components: true

discovery:

conversation:

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 3
  include:
    domains:
      - sensor
      - switch
      - media_player
      - climate
      - light
  exclude:
    entities:
      - sensor.averagepower
      - sensor.real_time_consumption_rognervegen_4a
      - sensor.voltagephase1
      - sensor.voltagephase2
      - sensor.voltagephase3
      - sensor.time_utc
      - sensor.date
      - sensor.internet_time
      - sensor.time_date
      - sensor.entur_johan_falkbergets_vei
      - sensor.entur_asveien_skole
      - sensor.entur_asveien_skole_platform_72800
      - sensor.entur_asveien_skole_platform_72801
      - sensor.entur_asveien_skole_platform_72798
      - sensor.entur_asveien_skole_platform_72799
      - sensor.entur_johan_falkbergets_vei_platform_73843
      - sensor.entur_johan_falkbergets_vei_platform_73845

history:
  include:
    domains:
      - switch
      - media_player
      - climate
      - light

logbook:

map:

sun:

default_config:

logger:
  default: info
  logs:
    hass_nabucasa: debug
    snitun: debug

weather:
  - platform: met

person:

air_quality:
  - platform: norway_air

input_number:
  powerconsumptionheating:
    name: PowerHeating
    min: 0
    max: 60000
  pricepowerconsumptionheating:
    name: PowerPrice
    min: 0
    max: 50
  kitchen_pid:
    name: PID output kitchen
    min: 0
    max: 100
  hall_heating_pid:
    name: PID output entrance
    min: 0
    max: 100
  guestbedroom_heating_pid:
    name: PID output guest bedroom
    min: 0
    max: 100
  guestbathroom_heating_pid:
    name: PID output guest bath room
    min: 0
    max: 100
  livingroom_heating_pid:
    name: PID output living room
    min: 0
    max: 100
  bedroom_heating_pid:
    name: PID output bedroom
    min: 0
    max: 100
  bathroom_heating_pid:
    name: PID output bath room
    min: 0
    max: 100
  bedroomolav_heating_pid:
    name: PID output bedroom Olav
    min: 0
    max: 100
  playroom_heating_pid:
    name: PID output play room
    min: 0
    max: 100
  laundry_heating_pid:
    name: PID output laundry
    min: 0
    max: 100
  workshop_heating_pid:
    name: PID output workshop
    min: 0
    max: 100

tibber:
  access_token: !secret tibber_access_token

utility_meter:
  energy:
    source: sensor.accumulatedconsumption
    cycle: daily

light:
  - platform: group
    name: bathroom_roof
    entities:
      - light.bathroom_01
      - light.bathroom_02
      - light.bathroom_03
      - light.bathroom_04

  - platform: group
    name: workshop_roof
    entities:
      - light.workshop_roof01
      - light.workshop_roof02
      
  - platform: template
    lights:
      dashboard_screen:
        turn_on:
        turn_off:
        set_level:

binary_sensor:
#  - platform: ring
  # - platform: template
  #   sensors:
  #     livingroom_motion_combined:
  #       friendly_name: "Bevegelse stue"
  #       device_class: motion
  #       value_template: >-
  #         {% if is_state('binary_sensor.livingroom_01_motion', 'on')
  #           or is_state('binary_sensor.livingroom_02_motion', 'on') %}
  #           true
  #         {% else %}
  #           false
  #         {% endif %}
  - platform: template
    sensors:
      roomba_bin_full:
        friendly_name: Roomba bin full
        value_template: "{{ states.vacuum.roomba.attributes.bin_full }}"
      roomba_bin_present:
        friendly_name: Roomba bin present
        value_template: "{{ states.vacuum.roomba.attributes.bin_present }}"
  - platform: workday
    country: "NO"
    workdays: [mon, tue, wed, thu, fri]
  - platform: mqtt
    name: dashboard_motion
    state_topic: any/value
  - platform: mqtt
    name: gamer_screensaver
    state_topic: computer/gamer/screensaver
  - platform: aurora
input_select:
  guestbedroom_mode:
    name: Gjesterom modus
    options:
      - Gjester
      - Ikke gjester
  ventilation_mode:
    name: Ventilasjons modus
    options:
      - Lav
      - Auto
      - Høy
camera:
#  - platform: ring

  - platform: generic
    still_image_url: !secret meteogram_png_url
    name: Meteogram

  - platform: local_file
    file_path: /config/www/images/imagedetection_walkway_latest.jpg
    name: latest detection walkway

  - platform: local_file
    file_path: /config/www/images/imagedetection_car_latest.jpg
    name: latest detection car

  - platform: mjpeg
    name: Ultimaker 3
    mjpeg_url: http://ultimaker01.local.elnan.do:8080/?action=stream

  - platform: generic
    name: Utendørs
    still_image_url: !secret nvr_1_still_image_url
    stream_source: !secret nvr_1_stream_source

  - platform: generic
    name: Verksted
    still_image_url: !secret nvr_2_still_image_url
    stream_source: !secret nvr_2_stream_source

  - name: tablet_gang
    platform: generic
    still_image_url: !secret tablet_gang_url

  - platform: proxy
    entity_id: camera.utendors
    name: imagedetection_walkway
    mode: crop
    max_stream_width: 580
    max_stream_height: 580
    max_image_width: 580
    max_image_height: 580
    image_left: 1171
    image_top: 500
    image_refresh_rate: 1.0
    

  - platform: proxy
    entity_id: camera.utendors
    name: imagedetection_car
    mode: crop
    max_stream_width: 320
    max_stream_height: 320
    max_image_width: 320
    max_image_height: 320
    image_left: 1100
    image_top: 330
    image_refresh_rate: 1.0

ffmpeg:

stream:

mobile_app:

wake_on_lan:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false

netatmo:
  client_id: !secret netatmo_api_key
  client_secret: !secret netatmo_secret_key

# ring:
#   username: !secret ring_username
#   password: !secret ring_password

tts:
  - platform: google_translate
    service_name: google_say
  - platform: google_cloud
    key_file: googlecloud.google.token
    language: nb-NO
    gender: female
    voice: nb-NO-Wavenet-A
    encoding: linear16
    profiles:
      - medium-bluetooth-speaker-class-device


cloud:
  google_actions:
    filter:
      include_entities:
        - light.kitchen_bench
        - light.kitchen_wire
        - light.livingroom_roof
    entity_config:
      light.kitchen_bench:
        name: Kjøkkenbenk
        aliases:
          - Benk
          - Kitchen bench
          - Bench
        room: kitchen
      light.livingroom_roof:
        name: Living room roof
        aliases:
          - Stuetak
        room: living room

webostv:
    - host: 10.20.0.60
      name: Living Room TV
      turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: 78:5D:C8:09:2F:47
      customize:
        sources:
          - TV
          - Apple TV
          - youtube
          - netflix
    - host: 10.20.0.61
      name: Game Room TV
      turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: 78:5D:C8:92:9a:d7
      customize:
        sources:
          - Nintendo Switch
          - PS4
          - Xbox
          - youtube
          - netflix
media_player:
  - platform: vlc_telnet
    name: Verksted
    host: !secret vlc_host
    port: 4212
    password: !secret vlc_pass
vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_pwd

# mqtt_statestream:
#   base_topic: homeassistant
#   publish_attributes: true
#   publish_timestamps: true
#   include:
#     domains:
#       - sensor
#       - light
#       - switch
#       - weather
#       - input_boolean
#       - input_select
#       - input_number

switch:
  - platform: mqtt
    name: "Workshop switch"
    state_topic: "home/workshop/switch1"
    command_topic: "home/workshop/switch1/set"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true

device_tracker:
  - platform: cisco_mobility_express
    host: !secret mobilityexpress_host
    username: !secret mobilityexpress_user
    password: !secret mobilityexpress_pass
    ssl: true
    verify_ssl: false

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

climate: !include climate.yaml
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_boolean: !include input_booleans.yaml

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwavegraph

image_processing:
  - platform: doods
    scan_interval: 1
    url: !secret doods_url
    detector: edgetpu
    source:
      - entity_id: camera.imagedetection_walkway  
    file_out:
      - "/config/www/images/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/config/www/images/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 50
    labels:
      - name: person
        confidence: 75
      - name: cat
        confidence: 40
  - platform: doods
    scan_interval: 1
    url: !secret doods_url
    detector: edgetpu
    source:
      - entity_id: camera.imagedetection_car
    file_out:
      - "/config/www/images/{{ camera_entity.split('.')[1] }}_latest.jpg"
      #- "/config/www/images/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 50
    labels:
      - name: car
        confidence: 55
        area: 
          top: 0.55
          covers: false
