homeassistant:
  name: Rognervegen 4
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 100
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  customize_glob:
    "sensor*exporting*":
      hidden: true
      homebridge_hidden: true
    "sensor.alarm*":
      hidden: true
      homebridge_hidden: true
    "sensor.*power_management*":
      hidden: true
      homebridge_hidden: true
    "sensor.*nano*heat*":
      hidden: true
      homebridge_hidden: true
    "sensor*sourcenodeid*":
      hidden: true
      homebridge_hidden: true
    "sensor*burglar*":
      hidden: true
      homebridge_hidden: true
    "sensor*ultraviolet*":
      hidden: true
      homebridge_hidden: true
    "binary_sensor*_motion":
      device_class: motion
    "sensor*temperature":
      device_class: temperature
    "sensor*humidity":
      device_class: humidity
    "binary_sensor*door":
      device_class: door
    "sensor*illuminance":
      device_class: illuminance

frontend:

config:

http:
  api_password: !secret http_password
  base_url: !secret base_url
  server_port: 4343
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - ::1
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.20.0.0/23
    - 2001:DB8:ABCD::/48
  ip_ban_enabled: True
  login_attempts_threshold: 5

influxdb:
  host: 127.0.0.1
  username: "home-assistant"
  password: !secret flux_db_password
  include:
    domains:
      - sensor
      - input_boolean
      - binary_sensor
      - light
      - switch
      - weather
      - input_number
  default_measurement: state
  tags:
    instance: prod
    source: hass
    
ios:
  push:
    categories:
      - name: 'Movement detected'
        identifier: 'Movement_detected'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'

zone:
  - name: Verksted
    latitude: !secret ha_latitude
    longitude: !secret ha_longitude
    radius: 3
    passive: true
  - name: Kjøkken
    latitude: !secret ha_latitude
    longitude: !secret ha_longitude
    radius: 3
    passive: true

apple_tv:

updater:
  include_used_components: true

discovery:

conversation:

recorder:
  db_url: !secret recorder_db_url

history:

logbook:

map:

sun:

weather:
  - platform: met

input_number:
  powerconsumptionheating:
    name: Slider
    min: 0
    max: 60000

tibber:
  access_token: !secret tibber_access_token

light:
  - platform: group
    name: bathroom_roof
    entities:
      - light.bathroom_01
      - light.bathroom_02
      - light.bathroom_03
      - light.bathroom_04
  - platform: group
    name: workshop_roof
    entities:
      - light.workshop_roof01
      - light.workshop_roof02

binary_sensor:
  - platform: ring
  - platform: template
    sensors:
      livingroom_motion_combined:
        friendly_name: "Bevegelse stue"
        device_class: motion
        value_template: >-
          {% if is_state('binary_sensor.livingroom_01_motion', 'on')
             or is_state('binary_sensor.livingroom_02_motion', 'on') %}
             true
          {% else %}
             false
          {% endif %}
  - platform: workday
    country: "NO"
    workdays: [mon, tue, wed, thu, fri]
    
input_select:
  guestbedroom_mode:
    name: Gjesterom modus
    options:
     - Gjester
     - Ikke gjester
     
camera:
  - platform: ring

  - platform: generic
    still_image_url: !secret meteogram_png_url
    name: Meteogram

  - platform: mjpeg
    name: Ultimaker 3
    mjpeg_url: http://ultimaker001.local.elnan.do:8080/?action=stream
    
  - platform: uvc
    nvr: !secret nvr_ip
    key: !secret nvr_key
    password: !secret nvr_password

openuv:
  api_key: !secret openuv_api_key

ffmpeg:

owntracks:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

ring:
  username: !secret ring_username
  password: !secret ring_password

tts:
  - platform: google

cloud:
  google_actions:
    filter:
      include_entities:
        - light.kitchen_bench
        - light.kitchen_wire
        - light.livingroom_roof
    entity_config:
      light.kitchen_bench:
        name: Kjøkkenbenk
        aliases:
         - Benk
         - Kitchen bench
         - Bench
        room: kitchen
      light.livingroom_roof:
        name: Living room roof
        aliases:
         - Stuetak
        room: living room

media_player:
  - platform: webostv
    host: 10.20.0.60
    name: Living Room TV
    timeout: 5
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 78:5D:C8:09:2F:47
    customize:
      sources:
        - livetv
        - youtube
        - netflix

notify:
  - platform: webostv
    host: 10.20.0.60
    name: Living_Room_TV_notify
    filename: webostv.conf
  - name: pushbullet_notify
    platform: pushbullet
    api_key: !secret pushbullet_api_key

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  include:
    domains:
      - sensor
      - light
      - switch
      - weather
      - input_boolean
      - input_select
      - input_number
      
switch:
  - platform: mqtt
    name: "Workshop switch"
    state_topic: "home/workshop/switch1"
    command_topic: "home/workshop/switch1/set"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
    
climate: !include climate.yaml
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_boolean: !include input_booleans.yaml
